### ISSUE TITLE
What exception should the Signer implementations throw?

### ISSUE THREAD

**Issue by MVrachev** [secure-systems-lab/securesystemslib#386] opened 2022-01-27 15:47 UTC
**Current behavior**:
We have defined the `Signer` interface: https://github.com/secure-systems-lab/securesystemslib/blob/602d3fcd59f726fc64e78a93430f427712d26ca4/securesystemslib/signer.py#L63 which is supposed to have multiple different implementations.

Currently, we have `SSLibSigner`: 
https://github.com/secure-systems-lab/securesystemslib/blob/602d3fcd59f726fc64e78a93430f427712d26ca4/securesystemslib/signer.py#L82 and proposed `GPGSigner` #341.

It's good to define what exceptions do we expect all of the Signer implementations to throw so that API functions that accept an object implementing this interface could know what exceptions to expect. 

_Inspired from comment: https://github.com/secure-systems-lab/securesystemslib/issues/386#issue-1116420165_

**Comment by lukpueh** [comment] 2024-03-14 10:56
duplicate of #468

**Closed by lukpueh** 2024-03-14 10:56 UTC
